version: "2"

services:
  database:
    image: postgres:10
    environment:
      - POSTGRES_USER=bitcoin
      - POSTGRES_PASSWORD=bitcoin
    volumes:
      - ./volumes/database:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  back:
    build: ./back
    depends_on:
      - database
      - redis
    ports:
      - 8000:8000
    environment:
      - DB_HOST=database
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_BACKEND_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379

  cronjob:
    build: ./back
    command: "python tasks.py"
    depends_on:
      - database
      - redis
    environment:
      - DB_HOST=database
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_BACKEND_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379

  frontend:
    build: ./front
    ports:
      - 80:80
